spring:
  batch:
    job:
      enabled: true
      name: ${job.name:NONE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/crypto-currency'
    username: 'root'
    password: '123456789'
  sql:
    init:
      mode: never