name: crypto-currency

on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - users: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradle clean :build -x test
      - name: Run batch
        run: java -jar -Dspring.batch.job.name=TickerSlackJob ./build/libs/cryto-currency.jar market=KRW-BTC